id: IC24C7F1C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T12:45:17+00:00'
last_modified: '2022-06-09T04:59:56.818104+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137833
  title: དཀར་མཛེས་བོད་རིགས་རང་སྐྱོང་ཁུལ་སློབ་གསོའི་ལོ་རྒྱུས་དེབ་ཐེར།（༡༩༩༡-༢༠༠༥）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E58F:
      image_group_id: I4PD4213
      title: Volume 1 of dkar mdzes bod rigs rang skyong khul slob gso'i lo rgyus
        deb ther/（1991-2005）
      total_pages: 314
      order: 1
      base_file: E58F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
