id: P007110
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137833
  title: དཀར་མཛེས་བོད་རིགས་རང་སྐྱོང་ཁུལ་སློབ་གསོའི་ལོ་རྒྱུས་དེབ་ཐེར།（༡༩༩༡-༢༠༠༥）
  author: ''
  volumes:
    5c8085e076cd45e29ad78a8242127f50:
      image_group_id: I4PD4213
      title: ''
      volume_number: 1
      total_pages: 314
ebook_metadata:
  title: དཀར་མཛེས་བོད་རིགས་རང་སྐྱོང་ཁུལ་སློབ་གསོའི་ལོ་རྒྱུས་དེབ་ཐེར།（༡༩༩༡-༢༠༠༥）
  author: ''
  sku: P007110
  cover: cover.jpg
  layers:
  - pagination
