id: opecha:P007110
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137833
  title: དཀར་མཛེས་བོད་རིགས་རང་སྐྱོང་ཁུལ་སློབ་གསོའི་ལོ་རྒྱུས་དེབ་ཐེར།（༡༩༩༡-༢༠༠༥）
  volume:
    320f42a191f54f56b3f12053d4a257a0:
      image_group_id: I4PD4213
      title: Volume 1 of dkar mdzes bod rigs rang skyong khul slob gso'i lo rgyus
        deb ther/（1991-2005）
      volume_number: 1
      total_pages: 314
  author: ''
ebook_metadata:
  title: དཀར་མཛེས་བོད་རིགས་རང་སྐྱོང་ཁུལ་སློབ་གསོའི་ལོ་རྒྱུས་དེབ་ཐེར།（༡༩༩༡-༢༠༠༥）
  author: ''
  sku: P007110
  cover: cover.jpg
  layers:
  - pagination
